### ISSUE TITLE
Chef::Handler::Datadog raised #<Net::OpenTimeout: execution expired>

### ISSUE THREAD

**Issue by kmf** [DataDog/chef-handler-datadog#106]
Running on 100's of nodes this is the, only one that gives this issue any ideas?

```Running handlers:
[2019-05-13T18:01:22+02:00] ERROR: Report handler Chef::Handler::Datadog raised #<Net::OpenTimeout: execution expired>
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/2.5.0/net/http.rb:937:in `initialize'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/2.5.0/net/http.rb:937:in `open'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/2.5.0/net/http.rb:935:in `connect'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/2.5.0/net/http.rb:909:in `start'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/dogapi-1.35.0/lib/dogapi/common.rb:97:in `connect'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/dogapi-1.35.0/lib/dogapi/common.rb:117:in `request'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/dogapi-1.35.0/lib/dogapi/v1/metric.rb:24:in `upload'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/dogapi-1.35.0/lib/dogapi/v1/metric.rb:29:in `submit_to_api'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/dogapi-1.35.0/lib/dogapi/v1/metric.rb:48:in `submit'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/dogapi-1.35.0/lib/dogapi/facade.rb:98:in `emit_points'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/dogapi-1.35.0/lib/dogapi/facade.rb:71:in `emit_point'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-handler-datadog-0.11.0/lib/chef/handler/datadog_chef_metrics.rb:38:in `emit_to_datadog'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-handler-datadog-0.11.0/lib/chef/handler/datadog.rb:77:in `send_report_to_datadog'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-handler-datadog-0.11.0/lib/chef/handler/datadog.rb:34:in `block in report'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-handler-datadog-0.11.0/lib/chef/handler/datadog.rb:32:in `each'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-handler-datadog-0.11.0/lib/chef/handler/datadog.rb:32:in `report'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/handler.rb:257:in `run_report_unsafe'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/handler.rb:245:in `run_report_safely'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/handler.rb:123:in `block in run_report_handlers'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/handler.rb:121:in `each'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/handler.rb:121:in `run_report_handlers'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/handler.rb:133:in `block in <class:Handler>'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/client.rb:445:in `block in run_completed_successfully'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/client.rb:444:in `each'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/client.rb:444:in `run_completed_successfully'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/client.rb:301:in `run'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/application.rb:279:in `block in run_chef_client'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/local_mode.rb:44:in `with_server_connectivity'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/application.rb:261:in `run_chef_client'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/application/client.rb:449:in `run_application'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/lib/chef/application.rb:66:in `run'
[2019-05-13T18:01:22+02:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.12.9/bin/chef-client:25:in `<top (required)>'
[2019-05-13T18:01:22+02:00] ERROR: /bin/chef-client:75:in `load'
[2019-05-13T18:01:22+02:00] ERROR: /bin/chef-client:75:in `<main>'
  - Chef::Handler::Datadog```

**Comment by remeh** [comment]
Hey @kmf, sorry for the late reply. 
Are you sure this node doesn't have any firewall which could cause this issue?
Is this still reproducible and not a transient connectivity issue?

**Comment by olivielpeau** [comment]
This should be fixed with https://github.com/DataDog/chef-handler-datadog/pull/98

**Comment by olivielpeau** [comment]
Closing as #98 should fix this, and will be part of the next release (`0.12.2`). @kmf if you still run into this error after upgrading to the upcoming `0.12.2` feel free to re-open this, thanks!
