### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by pdomagala** [DataDog/chef-handler-datadog#122]
Yesterday I noticed that our hourly scheduled chef-client task is failing, due to:

```
Running handlers:
[2020-02-28T11:16:15+00:00] ERROR: Running exception handlers
  - Chef::Handler::Datadog
Running handlers complete
[2020-02-28T11:16:17+00:00] ERROR: Exception handlers complete
Chef Client failed. 2 resources updated in 43 seconds
[2020-02-28T11:16:17+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2020-02-28T11:16:17+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-02-28T11:16:17+00:00] ERROR: 413 "Request Entity Too Large"
[2020-02-28T11:16:17+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

/var/chef/cache/chef-stacktrace.out:
```
Generated at 2020-02-28 11:16:17 +0000
Net::HTTPServerException: 413 "Request Entity Too Large"
/opt/chef/embedded/lib/ruby/2.4.0/net/http/response.rb:122:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/http.rb:152:in `request'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/http.rb:123:in `put'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/node.rb:596:in `save'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/client.rb:590:in `save_updated_node'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/client.rb:755:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/client.rb:457:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/client.rb:457:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/client.rb:441:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:58:in `load'
/usr/bin/chef-client:58:in `<main>'
```

What could go wrong? We didn't change anything. Where should I look for cause?
Chef v13.6.4, Datadog-cookbook v3.1.0

**Comment by jeremy-lq** [comment]
Hello, we'll need some addition information to troubleshoot this. Please open a [support ticket](https://www.datadoghq.com/support/) and we'll pick things up from there.
