### ISSUE TITLE
Handler fails with NoMethodError: undefined method `length' for nil:NilClass

### ISSUE THREAD

**Issue by PurrBiscuit** [DataDog/chef-handler-datadog#57]
We periodically run into this error during our chef runs.  We're using chef-client 11.18.6 and chef-handler-datadog-0.6.0.  Seems similar to this issue that was reported as being fixed with the 0.5.0 release.

https://github.com/DataDog/chef-handler-datadog/issues/51

It happens sporadically for us....maybe once or twice over the course of 200 or so chef runs.

```
[2015-02-25T16:46:08+00:00] INFO: Chef Handlers will be at: /var/chef/handlers
[2015-02-25T16:46:08+00:00] INFO: Processing remote_directory[/var/chef/handlers] action create (chef_handler::default line 23)
[2015-02-25T16:46:08+00:00] INFO: Processing cookbook_file[/var/chef/handlers/README] action create (dynamically defined)
[2015-02-25T16:46:08+00:00] INFO: Processing chef_gem[chef-handler-datadog] action install (datadog::dd-handler line 23)
[2015-02-25T16:46:08+00:00] INFO: Processing chef_handler[Chef::Handler::Datadog] action enable (datadog::dd-handler line 30)
[2015-02-25T16:46:08+00:00] INFO: Enabling chef_handler[Chef::Handler::Datadog] as a report handler
[2015-02-25T16:46:08+00:00] INFO: Enabling chef_handler[Chef::Handler::Datadog] as a exception handler
[2015-02-25T16:46:08+00:00] INFO: Processing cookbook_file[/var/chef/handlers/slack_handler.rb] action create (slack_handler::default line 17)
[2015-02-25T16:46:09+00:00] INFO: Processing chef_handler[Chef::Handler::Slack] action enable (slack_handler::default line 24)
[2015-02-25T16:46:09+00:00] INFO: Enabling chef_handler[Chef::Handler::Slack] as a report handler
[2015-02-25T16:46:09+00:00] INFO: Enabling chef_handler[Chef::Handler::Slack] as a exception handler
[2015-02-25T16:46:09+00:00] WARN: Cloning resource attributes for package[git] from prior resource (CHEF-3694)
[2015-02-25T16:46:09+00:00] WARN: Previous package[git]: /var/chef/cache/cookbooks/git/recipes/default.rb:24:in `from_file'
[2015-02-25T16:46:09+00:00] WARN: Current  package[git]: /var/chef/cache/cookbooks/base/recipes/packages.rb:2:in `block in from_file'
[2015-02-25T16:46:15+00:00] ERROR: Running exception handlers
[2015-02-25T16:46:15+00:00] ERROR: Report handler Chef::Handler::Datadog raised #<NoMethodError: undefined method `length' for nil:NilClass>
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-handler-datadog-0.6.0/lib/chef/handler/datadog.rb:196:in `emit_metrics_to_datadog'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-handler-datadog-0.6.0/lib/chef/handler/datadog.rb:27:in `report'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/handler.rb:226:in `run_report_unsafe'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/handler.rb:214:in `run_report_safely'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/handler.rb:118:in `block in run_exception_handlers'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/handler.rb:117:in `each'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/handler.rb:117:in `run_exception_handlers'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/handler.rb:127:in `block in <class:Handler>'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/client.rb:133:in `call'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/client.rb:133:in `block in run_failed'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/client.rb:132:in `each'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/client.rb:132:in `run_failed'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/client.rb:447:in `rescue in do_run'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/client.rb:459:in `do_run'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/client.rb:213:in `block in run'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/client.rb:207:in `fork'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/client.rb:207:in `run'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/application.rb:236:in `run_chef_client'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/application/client.rb:338:in `block in run_application'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/application/client.rb:327:in `loop'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/application/client.rb:327:in `run_application'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/lib/chef/application.rb:55:in `run'
[2015-02-25T16:46:15+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.6/bin/chef-client:26:in `<top (required)>'
[2015-02-25T16:46:15+00:00] ERROR: /usr/bin/chef-client:23:in `load'
[2015-02-25T16:46:15+00:00] ERROR: /usr/bin/chef-client:23:in `<main>'
[2015-02-25T16:46:16+00:00] ERROR: Exception handlers complete
```

**Comment by miketheman** [comment]
Thanks - I think this might be similar to what was submitted in #55 ?

**Comment by fromonesrc** [comment]
@miketheman why would this happen only sometimes? Looks like the failure is coming from here https://github.com/DataDog/chef-handler-datadog/blob/master/lib/chef/handler/datadog.rb#L196

**Comment by miketheman** [comment]
@fromonesrc I'm not certain. [This test](https://github.com/DataDog/chef-handler-datadog/blob/36e0d7e8169b856dadb8df215ca927d10b575a7f/spec/datadog_spec.rb#L355-L373) is meant to cover the occasions where the run_status length doesn't increase, but it's possible that it doesn't catch when some resources have started (notable the chef handlers themselves).

Although why it would only happen sporadically eludes me.

**Comment by miketheman** [comment]
@fromonesrc were you able to track down any further details on this?

**Comment by miketheman** [comment]
Closing this issue due to lack of response or further debugging data. Please reopen if there is more details for this case.
