### ISSUE TITLE
Issue with failed chef runs when compilation run fails

### ISSUE THREAD

**Issue by bigbam505** [DataDog/chef-handler-datadog#63]
As it turns out if you have a chef run that does not compile the handler also fails to send events.  Not sure if this is intended but currently it errors out on [this line](https://github.com/DataDog/chef-handler-datadog/blob/master/lib/chef/handler/datadog.rb#L196) because the resource list is apparently not created.  I would assume an event would still fire if this failed.  Its an easy fix, just not sure the intended behavior.

```
[2015-05-12T11:24:27-04:00] ERROR: Report handler Chef::Handler::Datadog raised #<NoMethodError: undefined method `length' for nil:NilClass>
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-handler-datadog-0.6.0/lib/chef/handler/datadog.rb:196:in `emit_metrics_to_datadog'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-handler-datadog-0.6.0/lib/chef/handler/datadog.rb:27:in `report'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/handler.rb:226:in `run_report_unsafe'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/handler.rb:214:in `run_report_safely'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/handler.rb:118:in `block in run_exception_handlers'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/handler.rb:117:in `each'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/handler.rb:117:in `run_exception_handlers'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/handler.rb:127:in `block in <class:Handler>'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:138:in `call'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:138:in `block in run_failed'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:137:in `each'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:137:in `run_failed'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:482:in `rescue in run'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:494:in `run'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:365:in `run_application'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/bin/chef-client:63:in `load'
[2015-05-12T11:24:27-04:00] ERROR: C:/opscode/chef/bin/chef-client:63:in `<main>'
[2015-05-12T11:24:27-04:00] ERROR: Exception handlers complete
[2015-05-12T11:24:27-04:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2015-05-12T11:24:27-04:00] INFO: Sending resource update report (run-id: 3c385608-ce80-4207-a667-3a1c5dc07544)
[2015-05-12T11:24:27-04:00] FATAL: NoMethodError: undefined method `url' for Chef::Resource::RemoteFile
[2015-05-12T11:24:35-04:00] INFO: Child process exited (pid: 4884)
[2015-05-12T11:24:36-04:00] INFO: Next chef-client run will happen in 1800.4645715359634 seconds
```

**Comment by miketheman** [comment]
I think this might be a duplicate of #55

**Comment by bigbam505** [comment]
Yup I believe this is a duplicate
