### ISSUE TITLE
Datadog raised #<NoMethodError: undefined method `length' for nil:NilClass>

### ISSUE THREAD

**Issue by jagatsingh** [DataDog/chef-handler-datadog#83]
We are getting below errors in Chef logs

2016-07-15T15:12:45+10:00] INFO: **\* Chef 11.18.12 ***

[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-handler-datadog-0.9.0/lib/chef/handler/datadog_chef_events.rb:148:in `build_event_data'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-handler-datadog-0.9.0/lib/chef/handler/datadog_chef_events.rb:72:in`emit_to_datadog'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-handler-datadog-0.9.0/lib/chef/handler/datadog.rb:74:in `send_report_to_datadog'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-handler-datadog-0.9.0/lib/chef/handler/datadog.rb:32:in`report'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:226:in `run_report_unsafe'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:214:in`run_report_safely'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:118:in `block in run_exception_handlers'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:117:in`each'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:117:in `run_exception_handlers'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:127:in`block in class:Handler'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:133:in `call'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:133:in`block in run_failed'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:132:in `each'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:132:in`run_failed'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:447:in `rescue in do_run'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:459:in`do_run'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:213:in `block in run'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:207:in`fork'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:207:in `run'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:236:in`run_chef_client'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:338:in `block in run_application'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:327:in`loop'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:327:in `run_application'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:55:in`run'
[2016-07-15T15:12:49+10:00] ERROR: /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
[2016-07-15T15:12:49+10:00] ERROR: /usr/bin/chef-client:38:in`load'
[2016-07-15T15:12:49+10:00] ERROR: /usr/bin/chef-client:38:in `<main>'
[2016-07-15T15:12:49+10:00] ERROR: Exception handlers complete
[2016-07-15T15:12:49+10:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-07-15T15:12:49+10:00] ERROR: undefined method`[]' for nil:NilClass
[2016-07-15T15:12:49+10:00] ERROR: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[2016-07-15T15:12:49+10:00] ERROR: Sleeping for 1800 seconds before trying again
[d760770@airflow-master-01 ~]$

**Comment by olivielpeau** [comment]
Hi @jagatsingh and thanks for opening this issue.

Could you give us some more details on your setup, i.e.:
- is this error occurring at every run of `chef-client` or only on some runs?
- have you enabled the handler through the [`datadog::dd-handler` recipe of chef-datadog](https://github.com/DataDog/chef-datadog/blob/master/recipes/dd-handler.rb), and if so which version of `chef-datadog` are you using?

Thanks!
